// AUTO-GENERATED — do not edit by hand.
// The metric catalog reachable via x402 (the "advanced" product tier), with the
// display metadata baked in so x402 mode needs no paid metadata calls.
// Regenerate: GLASSNODE_API_KEY=xxx pnpm run gen:x402-metrics
// Source: /v1/metadata/metrics?metadata_filter=metadata.products.exists(product,product=="advanced") + /v1/metadata/metric per path

export interface X402CatalogEntry {
  path: string;
  name: string;
  group: string;
  tags: string[];
}

export const X402_CATALOG: readonly X402CatalogEntry[] = [
  { path: "/addresses/active_count", name: "Number of Active Addresses", group: "Address Activity", tags: ["on-chain","addresses"] },
  { path: "/addresses/active_count_with_contracts", name: "Number of Active Addresses (with contracts)", group: "Address Activity", tags: ["on-chain","addresses"] },
  { path: "/addresses/activity_retention_rate", name: "Activity Retention Rate", group: "Retention", tags: ["on-chain","addresses","retention"] },
  { path: "/addresses/count", name: "Number of Addresses", group: "Address Growth", tags: ["on-chain","addresses"] },
  { path: "/addresses/holder_accumulation_ratio", name: "Holder Accumulation Ratio", group: "Retention", tags: ["on-chain","addresses"] },
  { path: "/addresses/holder_retention_rate", name: "Holder Retention Rate", group: "Retention", tags: ["on-chain","addresses","retention"] },
  { path: "/addresses/min_100_count", name: "Number of Addresses with Balance ≥ 100", group: "Addresses by Balance (Native)", tags: ["on-chain","addresses","cohorts"] },
  { path: "/addresses/min_100_usd_count", name: "Number of Addresses with Balance ≥ $100", group: "Addresses by Balance (USD)", tags: ["on-chain","addresses","cohorts"] },
  { path: "/addresses/min_100k_usd_count", name: "Number of Addresses with Balance ≥ $100k", group: "Addresses by Balance (USD)", tags: ["on-chain","addresses","cohorts"] },
  { path: "/addresses/min_10_count", name: "Number of Addresses with Balance ≥ 10", group: "Addresses by Balance (Native)", tags: ["on-chain","addresses","cohorts"] },
  { path: "/addresses/min_10_usd_count", name: "Number of Addresses with Balance ≥ $10", group: "Addresses by Balance (USD)", tags: ["on-chain","addresses","cohorts"] },
  { path: "/addresses/min_10k_count", name: "Number of Addresses with Balance ≥ 10k", group: "Addresses by Balance (Native)", tags: ["on-chain","addresses","cohorts"] },
  { path: "/addresses/min_10k_usd_count", name: "Number of Addresses with Balance ≥ $10k", group: "Addresses by Balance (USD)", tags: ["on-chain","addresses","cohorts"] },
  { path: "/addresses/min_1_count", name: "Number of Addresses with Balance ≥ 1", group: "Addresses by Balance (Native)", tags: ["on-chain","addresses","cohorts"] },
  { path: "/addresses/min_1_usd_count", name: "Number of Addresses with Balance ≥ $1", group: "Addresses by Balance (USD)", tags: ["on-chain","addresses","cohorts"] },
  { path: "/addresses/min_1k_count", name: "Number of Addresses with Balance ≥ 1k", group: "Addresses by Balance (Native)", tags: ["on-chain","addresses","cohorts"] },
  { path: "/addresses/min_1k_usd_count", name: "Number of Addresses with Balance ≥ $1k", group: "Addresses by Balance (USD)", tags: ["on-chain","addresses","cohorts"] },
  { path: "/addresses/min_1m_usd_count", name: "Number of Addresses with Balance ≥ $1M", group: "Addresses by Balance (USD)", tags: ["on-chain","addresses","cohorts"] },
  { path: "/addresses/min_32_count", name: "Number of Addresses with Balance ≥ 32 ETH", group: "Addresses by Balance (Native)", tags: ["on-chain","addresses","cohorts"] },
  { path: "/addresses/min_point_1_count", name: "Number of Addresses with Balance ≥ 0.1", group: "Addresses by Balance (Native)", tags: ["on-chain","addresses","cohorts"] },
  { path: "/addresses/min_point_zero_1_count", name: "Number of Addresses with Balance ≥ 0.01", group: "Addresses by Balance (Native)", tags: ["on-chain","addresses","cohorts"] },
  { path: "/addresses/new_non_zero_count", name: "Number of New Addresses", group: "Address Growth", tags: ["on-chain","addresses"] },
  { path: "/addresses/non_zero_count", name: "Number of Addresses with a Non-Zero Balance", group: "Addresses by Balance (Native)", tags: ["on-chain","addresses"] },
  { path: "/addresses/profit_count", name: "Number of Addresses in Profit", group: "Addresses in Profit/Loss", tags: ["on-chain","addresses","profit_loss","unrealized_profit_loss"] },
  { path: "/addresses/profit_relative", name: "Percent of Addresses in Profit", group: "Addresses in Profit/Loss", tags: ["on-chain","addresses","profit_loss","unrealized_profit_loss"] },
  { path: "/addresses/receiving_count", name: "Number of Receiving Addresses", group: "Address Activity", tags: ["on-chain","addresses"] },
  { path: "/addresses/sending_count", name: "Number of Sending Addresses", group: "Address Activity", tags: ["on-chain","addresses"] },
  { path: "/addresses/supply_distribution_relative", name: "Relative Address Supply Distribution", group: "Address Supply Bands", tags: ["on-chain","supply","cohorts","addresses"] },
  { path: "/blockchain/block_count", name: "Number of Blocks Mined", group: "Blocks", tags: ["on-chain","network_statistics"] },
  { path: "/blockchain/block_height", name: "Block Height", group: "Blocks", tags: ["on-chain","network_statistics"] },
  { path: "/blockchain/block_interval_mean", name: "Mean Block Interval", group: "Blocks", tags: ["on-chain","network_statistics"] },
  { path: "/blockchain/block_interval_median", name: "Median Block Interval", group: "Blocks", tags: ["on-chain","network_statistics"] },
  { path: "/blockchain/block_size_mean", name: "Mean Block Size", group: "Blocks", tags: ["on-chain","network_statistics"] },
  { path: "/blockchain/block_size_sum", name: "Total Block Size", group: "Blocks", tags: ["on-chain","network_statistics"] },
  { path: "/blockchain/utxo_count", name: "Total Numbers of UTXOs in the Network", group: "UTXO Growth", tags: ["on-chain","network_statistics"] },
  { path: "/blockchain/utxo_created_count", name: "Number of Created UTXOs", group: "UTXO Growth", tags: ["on-chain","network_statistics"] },
  { path: "/blockchain/utxo_created_value_mean", name: "Mean Value of Created UTXOs", group: "UTXO Volume", tags: ["on-chain","network_statistics","volume"] },
  { path: "/blockchain/utxo_created_value_median", name: "Median Value of Created UTXOs", group: "UTXO Volume", tags: ["on-chain","network_statistics","volume"] },
  { path: "/blockchain/utxo_created_value_sum", name: "Total Value of Created UTXOs", group: "UTXO Volume", tags: ["on-chain","network_statistics","volume"] },
  { path: "/blockchain/utxo_loss_count", name: "Number of UTXOs in Loss", group: "UTXOs in Profit/Loss", tags: ["on-chain","network_statistics","profit_loss","unrealized_profit_loss"] },
  { path: "/blockchain/utxo_profit_count", name: "Number of UTXOs in Profit", group: "UTXOs in Profit/Loss", tags: ["on-chain","network_statistics","profit_loss","unrealized_profit_loss"] },
  { path: "/blockchain/utxo_profit_relative", name: "Percent of UTXOs in Profit", group: "UTXOs in Profit/Loss", tags: ["on-chain","profit_loss","unrealized_profit_loss","network_statistics"] },
  { path: "/blockchain/utxo_spent_count", name: "Number of Spent UTXOs", group: "UTXO Growth", tags: ["on-chain","network_statistics"] },
  { path: "/blockchain/utxo_spent_value_mean", name: "Mean Value of Spent UTXOs", group: "UTXO Volume", tags: ["on-chain","network_statistics","transactions","volume"] },
  { path: "/blockchain/utxo_spent_value_median", name: "Median Value of Spent UTXOs", group: "UTXO Volume", tags: ["on-chain","transactions","volume","network_statistics"] },
  { path: "/blockchain/utxo_spent_value_sum", name: "Total Value of Spent UTXOs", group: "UTXO Volume", tags: ["on-chain","transactions","volume","network_statistics"] },
  { path: "/bridges/deposits_by_chain", name: "Bridges Deposits By Chain", group: "Bridges", tags: ["on-chain","bridges","volume"] },
  { path: "/bridges/net_volume_by_chain", name: "Bridges Net Flow By Chain", group: "Bridges", tags: ["on-chain","bridges","volume"] },
  { path: "/bridges/total_value_locked_by_chain", name: "Bridges TVL", group: "Bridges", tags: ["on-chain","bridges","defi"] },
  { path: "/bridges/total_value_locked_by_chain_relative", name: "Bridges TVL Relative", group: "Bridges", tags: ["on-chain","bridges","defi"] },
  { path: "/bridges/withdrawals_by_chain", name: "Bridges Withdrawals By Chain", group: "Bridges", tags: ["on-chain","bridges","volume"] },
  { path: "/defi/total_value_locked", name: "Total Value Locked in DeFi (TVL)", group: "DeFi & Protocols", tags: ["on-chain","defi","aggregate"] },
  { path: "/derivatives/futures_cme_open_interest_sum", name: "Futures CME Open Interest", group: "CME", tags: ["futures","open_interest","institutions"] },
  { path: "/derivatives/futures_cme_volume_daily_sum", name: "Futures CME Volume", group: "CME", tags: ["futures","volume","institutions"] },
  { path: "/derivatives/futures_estimated_leverage_ratio", name: "Futures Estimated Leverage Ratio", group: "Open Interest", tags: ["futures","open_interest","exchanges"] },
  { path: "/derivatives/futures_funding_rate_perpetual", name: "Futures Perpetual Funding Rate", group: "Funding Rates", tags: ["futures","funding"] },
  { path: "/derivatives/futures_funding_rate_perpetual_v2", name: "Futures Perpetual Funding Rate V2", group: "Funding Rates", tags: ["futures","funding"] },
  { path: "/derivatives/futures_liquidated_total_volume_sum", name: "Futures Total Liquidations (Total)", group: "Liquidations", tags: ["futures","liquidations","volume"] },
  { path: "/derivatives/futures_liquidated_volume_long_relative", name: "Futures Long Liquidations Dominance", group: "Liquidations", tags: ["futures","liquidations"] },
  { path: "/derivatives/futures_liquidated_volume_long_sum", name: "Futures Long Liquidations (Total)", group: "Liquidations", tags: ["futures","liquidations","volume"] },
  { path: "/derivatives/futures_liquidated_volume_short_sum", name: "Futures Short Liquidations (Total)", group: "Liquidations", tags: ["futures","liquidations","volume"] },
  { path: "/derivatives/futures_open_interest_latest", name: "Futures Open Interest (Current)", group: "Open Interest", tags: ["futures","open_interest"] },
  { path: "/derivatives/futures_open_interest_perpetual_sum", name: "Futures Open Interest Perpetual", group: "Open Interest", tags: ["futures","open_interest"] },
  { path: "/derivatives/futures_open_interest_sum", name: "Futures Open Interest", group: "Open Interest", tags: ["futures","open_interest"] },
  { path: "/derivatives/futures_volume_daily_latest", name: "Futures Volume 24h (Latest)", group: "Volume", tags: ["futures","volume"] },
  { path: "/derivatives/futures_volume_daily_perpetual_sum", name: "Futures Volume Perpetual 24h", group: "Volume", tags: ["futures","volume"] },
  { path: "/derivatives/futures_volume_daily_sum", name: "Futures Volume 24h", group: "Volume", tags: ["futures","volume"] },
  { path: "/derivatives/options_cme_open_interest_sum", name: "Options CME Open Interest", group: "CME", tags: ["options","open_interest","institutions"] },
  { path: "/derivatives/options_cme_volume_daily_sum", name: "Options CME Volume", group: "CME", tags: ["options","volume","institutions"] },
  { path: "/derivatives/options_open_interest_put_call_ratio", name: "Options Open Interest Put/Call Ratio", group: "Put/Call Ratios", tags: ["options","open_interest"] },
  { path: "/derivatives/options_open_interest_sum", name: "Options Open Interest", group: "Open Interest", tags: ["options","open_interest"] },
  { path: "/derivatives/options_volume_daily_sum", name: "Options Volume 24h", group: "Volume", tags: ["options","volume"] },
  { path: "/derivatives/options_volume_put_call_ratio", name: "Options Volume Put/Call Ratio", group: "Put/Call Ratios", tags: ["options"] },
  { path: "/distribution/balance_1pct_holders", name: "Percent of Supply Held by Top 1% Addresses", group: "Wealth Distribution", tags: ["on-chain","supply","cohorts"] },
  { path: "/distribution/balance_bhutan_government", name: "Bhutan Government Balance", group: "Governments & Companies", tags: ["on-chain","governments","entities","treasuries"] },
  { path: "/distribution/balance_donald_trump", name: "Donald Trump Balance", group: "Entity Balances", tags: ["on-chain","entities"] },
  { path: "/distribution/balance_el_salvador", name: "El Salvador Government Balance", group: "Governments & Companies", tags: ["on-chain","entities","governments","treasuries"] },
  { path: "/distribution/balance_exchanges", name: "Balance on Exchanges (Total)", group: "Exchange Balances", tags: ["on-chain","exchanges","entities"] },
  { path: "/distribution/balance_exchanges_relative", name: "Percent Balance on Exchanges", group: "Exchange Balances", tags: ["on-chain","exchanges","supply","entities"] },
  { path: "/distribution/balance_german_government", name: "German Government Balance", group: "Governments & Companies", tags: ["on-chain","governments","entities","treasuries"] },
  { path: "/distribution/balance_luna_foundation_guard", name: "Luna Foundation Guard Balance", group: "Governments & Companies", tags: ["on-chain","treasuries","entities"] },
  { path: "/distribution/balance_miners_change", name: "Miner Net Position Change", group: "Miner Balances", tags: ["on-chain","mining","entities","supply"] },
  { path: "/distribution/balance_miners_sum", name: "Balance in Miner Wallets", group: "Miner Balances", tags: ["on-chain","mining","entities","supply"] },
  { path: "/distribution/balance_mtgox_trustee", name: "Mt. Gox Trustee Balance", group: "Governments & Companies", tags: ["on-chain","entities","companies","treasuries"] },
  { path: "/distribution/balance_us_government", name: "US Government Balance", group: "Governments & Companies", tags: ["on-chain","governments","entities","treasuries"] },
  { path: "/distribution/balance_wbtc", name: "Wrapped BTC (WBTC) Balance", group: "Governments & Companies", tags: ["on-chain","entities","companies"] },
  { path: "/distribution/exchange_net_position_change", name: "Exchange Net Position Change", group: "Exchange Balances", tags: ["on-chain","exchanges","supply","entities"] },
  { path: "/distribution/gini", name: "Gini Coefficient", group: "Wealth Distribution", tags: ["on-chain"] },
  { path: "/distribution/herfindahl", name: "Herfindahl Index", group: "Wealth Distribution", tags: ["on-chain","supply"] },
  { path: "/distribution/supply_contracts", name: "Percent of Supply in Smart Contracts", group: "Smart Contracts", tags: ["on-chain","supply"] },
  { path: "/entities/min_1k_count", name: "Number of Entities With Balance ≥ 1k", group: "Entity Supply Bands", tags: ["on-chain","entities","cohorts"] },
  { path: "/entities/supply_distribution_relative", name: "Entities Supply Distribution", group: "Entity Supply Bands", tags: ["on-chain","supply","entities","cohorts"] },
  { path: "/eth2/active_validators_count", name: "Active Validators", group: "Validators", tags: ["on-chain","staking"] },
  { path: "/eth2/attestation_count", name: "Attestation Count", group: "Consensus", tags: ["on-chain","staking","network_statistics"] },
  { path: "/eth2/deposited_by_provider_volume_sum", name: "ETH 2.0 Total Value Staked by Provider", group: "Staking", tags: ["on-chain","staking","volume","entities"] },
  { path: "/eth2/deposits_count", name: "Staking Deposits", group: "Staking", tags: ["on-chain","staking"] },
  { path: "/eth2/effective_balance_sum", name: "Total Effective Balance", group: "Staking", tags: ["on-chain","staking"] },
  { path: "/eth2/epoch_height", name: "Epoch Height", group: "Blocks", tags: ["on-chain","staking","network_statistics"] },
  { path: "/eth2/estimated_annual_issuance", name: "Estimated Annual Issuance", group: "Supply Dynamics", tags: ["on-chain","staking","supply","network_statistics"] },
  { path: "/eth2/estimated_annual_issuance_roi_per_validator", name: "Estimated Annual Issuance ROI per validator", group: "Validators", tags: ["on-chain","staking"] },
  { path: "/eth2/missed_blocks_count", name: "Missed Blocks", group: "Blocks", tags: ["on-chain","staking","network_statistics"] },
  { path: "/eth2/orphaned_blocks_count", name: "Orphaned Blocks", group: "Blocks", tags: ["on-chain","staking","network_statistics"] },
  { path: "/eth2/participation_rate_mean", name: "Participation Rate", group: "Validators", tags: ["on-chain","staking","network_statistics"] },
  { path: "/eth2/slashings_count", name: "Slashing Event Count", group: "Consensus", tags: ["on-chain","staking","network_statistics"] },
  { path: "/eth2/slot_height", name: "Slot Height", group: "Blocks", tags: ["on-chain","network_statistics","staking"] },
  { path: "/eth2/stake_effectiveness_mean", name: "Stake Effectiveness", group: "Staking", tags: ["on-chain","staking"] },
  { path: "/eth2/staking_deposits_count", name: "ETH 2.0 Number of New Deposits", group: "Staking", tags: ["on-chain","staking","transactions"] },
  { path: "/eth2/staking_total_deposits_count", name: "ETH 2.0 Total Number of Deposits", group: "Staking", tags: ["on-chain","staking"] },
  { path: "/eth2/staking_total_validators_count", name: "ETH 2.0 Total Number of Validators", group: "Validators", tags: ["on-chain","staking"] },
  { path: "/eth2/staking_total_volume_sum", name: "ETH 2.0 Total Value Staked", group: "Staking", tags: ["on-chain","staking","volume"] },
  { path: "/eth2/staking_validators_count", name: "ETH 2.0 Number of New Validators", group: "Validators", tags: ["on-chain","staking"] },
  { path: "/eth2/staking_volume_sum", name: "ETH 2.0 Amount of New Value Staked", group: "Staking", tags: ["on-chain","staking","volume"] },
  { path: "/eth2/validator_balance_mean", name: "Average Validator Balance", group: "Validators", tags: ["on-chain","staking"] },
  { path: "/eth2/voluntary_exit_count", name: "Voluntary Exit Count", group: "Consensus", tags: ["on-chain","staking","network_statistics"] },
  { path: "/fees/fee_ratio_multiple", name: "Fee Ratio Multiple (FRM)", group: "Fees", tags: ["on-chain","fees","mining"] },
  { path: "/fees/gas_limit_tx_mean", name: "Mean Transaction Gas Limit", group: "Gas", tags: ["on-chain","gas","transactions","fees"] },
  { path: "/fees/gas_limit_tx_median", name: "Median Transaction Gas Limit", group: "Gas", tags: ["on-chain","gas","fees","transactions"] },
  { path: "/fees/gas_price_mean", name: "Mean Transaction Gas Price", group: "Gas", tags: ["on-chain","gas","fees"] },
  { path: "/fees/gas_price_median", name: "Median Transaction Gas Price", group: "Gas", tags: ["on-chain","gas","fees"] },
  { path: "/fees/gas_used_mean", name: "Mean Gas Used", group: "Gas", tags: ["on-chain","gas","fees"] },
  { path: "/fees/gas_used_median", name: "Median Gas Used", group: "Gas", tags: ["on-chain","gas","fees"] },
  { path: "/fees/gas_used_sum", name: "Total Gas Used", group: "Gas", tags: ["on-chain","gas","fees"] },
  { path: "/fees/gas_used_sum_nfts", name: "Gas Usage by NFTs (Absolute)", group: "Gas", tags: ["on-chain","gas","fees"] },
  { path: "/fees/gas_used_sum_nfts_relative", name: "Gas Usage by NFTs (Relative)", group: "Gas", tags: ["on-chain","gas","fees"] },
  { path: "/fees/tx_types_breakdown_relative", name: "Ethereum Gas Usage by Transaction Type (Relative)", group: "Gas", tags: ["on-chain","gas","fees","transactions"] },
  { path: "/fees/tx_types_breakdown_sum", name: "Ethereum Gas Usage by Transaction Type (Absolute)", group: "Gas", tags: ["on-chain","gas","fees","transactions"] },
  { path: "/fees/volume_mean", name: "Mean Transaction Fees", group: "Fees", tags: ["on-chain","fees","transactions","mining"] },
  { path: "/fees/volume_median", name: "Median Transaction Fees", group: "Fees", tags: ["on-chain","fees","transactions","mining"] },
  { path: "/fees/volume_sum", name: "Total Transaction Fees", group: "Fees", tags: ["on-chain","fees","mining","transactions"] },
  { path: "/indicators/accumulation_trend_score", name: "Accumulation Trend Score", group: "Indicators", tags: ["on-chain","entities"] },
  { path: "/indicators/asol", name: "Average Spent Output Lifespan (ASOL)", group: "Spent Output Lifespan", tags: ["on-chain","lifespan"] },
  { path: "/indicators/average_dormancy", name: "Average Coin Dormancy", group: "Dormancy", tags: ["on-chain","lifespan"] },
  { path: "/indicators/average_dormancy_supply_adjusted", name: "Supply-Adjusted Dormancy", group: "Dormancy", tags: ["on-chain","lifespan"] },
  { path: "/indicators/balanced_price_usd", name: "Balanced Price", group: "Pricing Models", tags: ["on-chain","price","valuation"] },
  { path: "/indicators/cdd", name: "Coin Days Destroyed (CDD)", group: "Coin Days Destroyed", tags: ["on-chain","lifespan"] },
  { path: "/indicators/cdd90_age_adjusted", name: "90D Coin Days Destroyed (CDD-90)", group: "Coin Days Destroyed", tags: ["on-chain","lifespan"] },
  { path: "/indicators/cdd_supply_adjusted", name: "Supply-Adjusted CDD", group: "Coin Days Destroyed", tags: ["on-chain","lifespan"] },
  { path: "/indicators/cdd_supply_adjusted_binary", name: "Binary CDD", group: "Coin Days Destroyed", tags: ["on-chain","lifespan"] },
  { path: "/indicators/coin_blocks_created", name: "Coin Blocks Created (CBC)", group: "Coin Blocks", tags: ["on-chain","lifespan"] },
  { path: "/indicators/coin_blocks_destroyed", name: "Coin Blocks Destroyed", group: "Coin Blocks", tags: ["on-chain","lifespan"] },
  { path: "/indicators/cost_basis_distribution_heatmap", name: "Cost Basis Distribution Heatmap", group: "Supply", tags: ["on-chain","supply","cohorts"] },
  { path: "/indicators/cvdd", name: "Cumulative Value-Days Destroyed (CVDD)", group: "Indicators", tags: ["on-chain","lifespan","valuation"] },
  { path: "/indicators/cyd", name: "Coin Years Destroyed", group: "Coin Days Destroyed", tags: ["on-chain","lifespan"] },
  { path: "/indicators/cyd_supply_adjusted", name: "Supply-Adjusted Coin Years Destroyed", group: "Coin Days Destroyed", tags: ["on-chain","lifespan"] },
  { path: "/indicators/difficulty_ribbon", name: "Difficulty Ribbon", group: "Ribbons", tags: ["on-chain","mining","valuation"] },
  { path: "/indicators/difficulty_ribbon_compression", name: "Difficulty Ribbon Compression", group: "Ribbons", tags: ["on-chain","mining","valuation"] },
  { path: "/indicators/dormancy_flow", name: "Dormancy Flow", group: "Dormancy", tags: ["on-chain","lifespan","valuation"] },
  { path: "/indicators/fear_greed", name: "Fear & Greed Index", group: "Indicators", tags: ["spot","valuation"] },
  { path: "/indicators/hash_ribbon", name: "Hash Ribbon", group: "Ribbons", tags: ["on-chain","mining","valuation"] },
  { path: "/indicators/hodled_lost_coins", name: "Hodled or Lost Coins", group: "Liveliness", tags: ["on-chain","supply","lifespan"] },
  { path: "/indicators/hodler_net_position_change", name: "Hodler Net Position Change", group: "Liveliness", tags: ["on-chain","supply","cohorts","long_term_holder"] },
  { path: "/indicators/investor_capitalization", name: "Investor Capitalization", group: "Indicators", tags: ["on-chain","valuation"] },
  { path: "/indicators/liveliness", name: "Liveliness", group: "Liveliness", tags: ["on-chain","lifespan"] },
  { path: "/indicators/msol", name: "Median Spent Output Lifespan (MSOL)", group: "Spent Output Lifespan", tags: ["on-chain","lifespan"] },
  { path: "/indicators/net_realized_profit_loss", name: "Net Realized Profit/Loss", group: "Realized Profit/Loss", tags: ["on-chain","realized_profit_loss","profit_loss"] },
  { path: "/indicators/net_unrealized_profit_loss", name: "Net Unrealized Profit/Loss (NUPL)", group: "Unrealized Profit/Loss", tags: ["on-chain","valuation","profit_loss","unrealized_profit_loss"] },
  { path: "/indicators/nupl_less_155", name: "Short Term Holder NUPL", group: "Profit/Loss", tags: ["on-chain","unrealized_profit_loss","profit_loss","valuation","short_term_holder","cohorts"] },
  { path: "/indicators/nupl_more_155", name: "Long Term Holder NUPL", group: "Profit/Loss", tags: ["on-chain","valuation","profit_loss","unrealized_profit_loss","long_term_holder","cohorts"] },
  { path: "/indicators/nvt", name: "Network Value to Transactions Ratio (NVT)", group: "NVT", tags: ["on-chain","valuation"] },
  { path: "/indicators/nvts", name: "Network Value to Transactions Signal", group: "NVT", tags: ["on-chain","valuation"] },
  { path: "/indicators/pi_cycle_top", name: "Pi Cycle Top Indicator", group: "Indicators", tags: ["on-chain","valuation"] },
  { path: "/indicators/power_law", name: "Power-Law Model", group: "Indicators", tags: ["on-chain","valuation"] },
  { path: "/indicators/puell_multiple", name: "Puell Multiple", group: "Indicators", tags: ["on-chain","valuation","mining"] },
  { path: "/indicators/realized_loss", name: "Realized Loss", group: "Realized Profit/Loss", tags: ["on-chain","realized_profit_loss","profit_loss"] },
  { path: "/indicators/realized_profit", name: "Realized Profit", group: "Realized Profit/Loss", tags: ["on-chain","realized_profit_loss","profit_loss"] },
  { path: "/indicators/realized_profit_loss_ratio", name: "Realized Profit/Loss Ratio", group: "Realized Profit/Loss", tags: ["on-chain","profit_loss","realized_profit_loss","valuation"] },
  { path: "/indicators/realized_profits_to_value_ratio", name: "Realized Profits-to-Value (RPV) Ratio", group: "Realized Profit/Loss", tags: ["on-chain","valuation","profit_loss","realized_profit_loss"] },
  { path: "/indicators/reserve_risk", name: "Reserve Risk", group: "Reserve Risk", tags: ["on-chain","valuation"] },
  { path: "/indicators/rhodl_ratio", name: "Realized HODL Ratio", group: "Indicators", tags: ["on-chain","valuation"] },
  { path: "/indicators/seller_exhaustion_constant", name: "Seller Exhaustion Constant", group: "Indicators", tags: ["on-chain","valuation","profit_loss","unrealized_profit_loss"] },
  { path: "/indicators/soab", name: "Spent Output Age Bands", group: "Spent Output Lifespan", tags: ["on-chain","lifespan","cohorts"] },
  { path: "/indicators/sol_1d_1w", name: "Spent Output Lifespan 1d-1w", group: "Spent Output Lifespan", tags: ["on-chain","lifespan","cohorts"] },
  { path: "/indicators/sol_1h", name: "Spent Output Lifespan < 1h", group: "Spent Output Lifespan", tags: ["on-chain","lifespan","cohorts"] },
  { path: "/indicators/sol_1h_24h", name: "Spent Output Lifespan 1h-24h", group: "Spent Output Lifespan", tags: ["on-chain","lifespan","cohorts"] },
  { path: "/indicators/sol_1m_3m", name: "Spent Output Lifespan 1m-3m", group: "Spent Output Lifespan", tags: ["on-chain","lifespan","cohorts"] },
  { path: "/indicators/sol_1w_1m", name: "Spent Output Lifespan 1w-1m", group: "Spent Output Lifespan", tags: ["on-chain","lifespan","cohorts"] },
  { path: "/indicators/sol_1y_2y", name: "Spent Output Lifespan 1y-2y", group: "Spent Output Lifespan", tags: ["on-chain","lifespan","cohorts"] },
  { path: "/indicators/sol_2y_3y", name: "Spent Output Lifespan 2y-3y", group: "Spent Output Lifespan", tags: ["on-chain","lifespan","cohorts"] },
  { path: "/indicators/sol_3m_6m", name: "Spent Output Lifespan 3m-6m", group: "Spent Output Lifespan", tags: ["on-chain","lifespan","cohorts"] },
  { path: "/indicators/sol_3y_5y", name: "Spent Output Lifespan 3y-5y", group: "Spent Output Lifespan", tags: ["on-chain","lifespan","cohorts"] },
  { path: "/indicators/sol_5y_7y", name: "Spent Output Lifespan 5y-7y", group: "Spent Output Lifespan", tags: ["on-chain","lifespan","cohorts","transactions"] },
  { path: "/indicators/sol_6m_12m", name: "Spent Output Lifespan 6m-12m", group: "Spent Output Lifespan", tags: ["on-chain","lifespan","cohorts"] },
  { path: "/indicators/sol_7y_10y", name: "Spent Output Lifespan 7y-10y", group: "Spent Output Lifespan", tags: ["on-chain","lifespan","cohorts"] },
  { path: "/indicators/sol_more_10y", name: "Spent Output Lifespan > 10y", group: "Spent Output Lifespan", tags: ["on-chain","lifespan","cohorts"] },
  { path: "/indicators/sopr", name: "Spent Output Profit Ratio (SOPR)", group: "SOPR", tags: ["on-chain","valuation","profit_loss","realized_profit_loss"] },
  { path: "/indicators/sopr_adjusted", name: "Adjusted SOPR (aSOPR)", group: "SOPR", tags: ["on-chain","valuation","profit_loss","realized_profit_loss"] },
  { path: "/indicators/ssr", name: "Stablecoin Supply Ratio (SSR)", group: "Stablecoin Supply Ratio", tags: ["on-chain","valuation","supply"] },
  { path: "/indicators/ssr_oscillator", name: "Stablecoin Supply Ratio (SSR) Oscillator", group: "Stablecoin Supply Ratio", tags: ["on-chain","valuation"] },
  { path: "/indicators/stock_to_flow_deflection", name: "Stock-to-Flow Deflection", group: "Stock-to-Flow", tags: ["on-chain","valuation"] },
  { path: "/indicators/stock_to_flow_ratio", name: "Stock-to-Flow Ratio", group: "Stock-to-Flow", tags: ["on-chain","valuation"] },
  { path: "/indicators/svab", name: "Spent Volume Age Bands (SVAB)", group: "Spent Volume Lifespan", tags: ["on-chain","lifespan","cohorts","volume"] },
  { path: "/indicators/svl_1d_1w", name: "Spent Volume Lifespan 1d-1w", group: "Spent Volume Lifespan", tags: ["on-chain","lifespan","volume","cohorts"] },
  { path: "/indicators/svl_1h", name: "Spent Volume Lifespan < 1h", group: "Spent Volume Lifespan", tags: ["on-chain","lifespan","volume","cohorts"] },
  { path: "/indicators/svl_1h_24h", name: "Spent Volume Lifespan 1h-24h", group: "Spent Volume Lifespan", tags: ["on-chain","lifespan","volume","cohorts"] },
  { path: "/indicators/svl_1m_3m", name: "Spent Volume Lifespan 1m-3m", group: "Spent Volume Lifespan", tags: ["on-chain","lifespan","volume","cohorts"] },
  { path: "/indicators/svl_1w_1m", name: "Spent Volume Lifespan 1w-1m", group: "Spent Volume Lifespan", tags: ["on-chain","lifespan","volume","cohorts"] },
  { path: "/indicators/svl_1y_2y", name: "Spent Volume Lifespan 1y-2y", group: "Spent Volume Lifespan", tags: ["on-chain","lifespan","volume","cohorts"] },
  { path: "/indicators/svl_2y_3y", name: "Spent Volume Lifespan 2y-3y", group: "Spent Volume Lifespan", tags: ["on-chain","lifespan","volume","cohorts"] },
  { path: "/indicators/svl_3m_6m", name: "Spent Volume Lifespan 3m-6m", group: "Spent Volume Lifespan", tags: ["on-chain","lifespan","volume","cohorts"] },
  { path: "/indicators/svl_3y_5y", name: "Spent Volume Lifespan 3y-5y", group: "Spent Volume Lifespan", tags: ["on-chain","lifespan","volume","cohorts"] },
  { path: "/indicators/svl_5y_7y", name: "Spent Volume Lifespan 5y-7y", group: "Spent Volume Lifespan", tags: ["on-chain","lifespan","volume","cohorts"] },
  { path: "/indicators/svl_6m_12m", name: "Spent Volume Lifespan 6m-12m", group: "Spent Volume Lifespan", tags: ["on-chain","lifespan","volume","cohorts"] },
  { path: "/indicators/svl_7y_10y", name: "Spent Volume Lifespan 7y-10y", group: "Spent Volume Lifespan", tags: ["on-chain","lifespan","volume","cohorts"] },
  { path: "/indicators/svl_more_10y", name: "Spent Volume Lifespan > 10y", group: "Spent Volume Lifespan", tags: ["on-chain","lifespan","volume","cohorts"] },
  { path: "/indicators/unrealized_loss", name: "Relative Unrealized Loss", group: "Unrealized Profit/Loss", tags: ["on-chain","unrealized_profit_loss","profit_loss","valuation"] },
  { path: "/indicators/unrealized_profit", name: "Relative Unrealized Profit", group: "Unrealized Profit/Loss", tags: ["on-chain","unrealized_profit_loss","profit_loss","valuation"] },
  { path: "/indicators/utxo_realized_price_distribution_ath", name: "UTXO Realized Price Distribution (URPD): ATH-Partitioned", group: "Price Distribution", tags: ["on-chain","supply","cohorts"] },
  { path: "/indicators/velocity", name: "Velocity", group: "NVT", tags: ["on-chain","valuation"] },
  { path: "/institutions/purpose_etf_aum_sum", name: "Purpose Bitcoin ETF AUM", group: "Canadian ETF", tags: ["etf","institutions","entities","companies"] },
  { path: "/institutions/purpose_etf_flows_sum", name: "Purpose Bitcoin ETF Flows", group: "Canadian ETF", tags: ["etf","institutions","entities","companies"] },
  { path: "/institutions/purpose_etf_holdings_sum", name: "Purpose Bitcoin ETF Holdings", group: "Canadian ETF", tags: ["etf","institutions","entities","companies"] },
  { path: "/institutions/us_spot_etf_balances_all", name: "US Spot ETF Balances", group: "ETFs", tags: ["etf","institutions","entities","companies"] },
  { path: "/institutions/us_spot_etf_balances_latest", name: "US Spot ETF Balances (Latest 24h)", group: "ETFs", tags: ["etf","institutions","entities","companies"] },
  { path: "/institutions/us_spot_etf_flows_all", name: "US Spot ETF Flows", group: "ETFs", tags: ["etf","institutions","entities","companies"] },
  { path: "/institutions/us_spot_etf_flows_net", name: "US Spot ETF Net Flows", group: "ETFs", tags: ["etf","institutions","entities","companies"] },
  { path: "/lightning/base_fee_median", name: "Lightning Network Base Fee (Median)", group: "Lightning Fees", tags: ["on-chain","lightning","fees"] },
  { path: "/lightning/channel_size_mean", name: "Lightning Network Channel Size (Mean)", group: "Lightning Channels", tags: ["on-chain","lightning"] },
  { path: "/lightning/channel_size_median", name: "Lightning Network Channel Size (Median)", group: "Lightning Channels", tags: ["on-chain","lightning"] },
  { path: "/lightning/channels_count", name: "Lightning Network Number of Channels", group: "Lightning Channels", tags: ["on-chain","lightning"] },
  { path: "/lightning/fee_rate_median", name: "Lightning Network Fee Rate (Median)", group: "Lightning Fees", tags: ["on-chain","lightning","fees"] },
  { path: "/lightning/gini_capacity_distribution", name: "Lightning Network Gini Coefficient (Capacity Distribution)", group: "Lightning Capacity", tags: ["on-chain","lightning"] },
  { path: "/lightning/gini_channel_distribution", name: "Lightning Network Gini Coefficient (Channel Distribution)", group: "Lightning Channels", tags: ["on-chain","lightning"] },
  { path: "/lightning/network_capacity_sum", name: "Lightning Network Capacity", group: "Lightning Capacity", tags: ["on-chain","lightning"] },
  { path: "/lightning/node_connectivity", name: "Lightning Network Node Connectivity", group: "Lightning Nodes", tags: ["on-chain","lightning"] },
  { path: "/lightning/nodes_count", name: "Lightning Network Number of Nodes", group: "Lightning Nodes", tags: ["on-chain","lightning"] },
  { path: "/market/amer_30d_price_change", name: "US Month-over-Month Price Change", group: "Price", tags: ["spot","price"] },
  { path: "/market/apac_30d_price_change", name: "Asia Month-over-Month Price Change", group: "Price", tags: ["spot","price"] },
  { path: "/market/deltacap_usd", name: "Delta Cap", group: "Realized Cap & Price", tags: ["on-chain","valuation"] },
  { path: "/market/emea_30d_price_change", name: "EU Month-over-Month Price Change", group: "Price", tags: ["spot","price"] },
  { path: "/market/hodl_cave", name: "HODL Cave", group: "HODL Waves", tags: ["spot","cohorts"] },
  { path: "/market/marketcap_realized_usd", name: "Realized Cap", group: "Realized Cap & Price", tags: ["on-chain","valuation"] },
  { path: "/market/marketcap_usd", name: "Market Cap", group: "Market Cap", tags: ["spot","valuation"] },
  { path: "/market/mvrv", name: "Market Value to Realized Value Ratio (MVRV)", group: "MVRV", tags: ["on-chain","valuation","profit_loss","unrealized_profit_loss"] },
  { path: "/market/mvrv_less_155", name: "Short Term Holder MVRV", group: "MVRV", tags: ["on-chain","valuation","short_term_holder","cohorts","profit_loss","unrealized_profit_loss"] },
  { path: "/market/mvrv_more_155", name: "Long Term Holder MVRV", group: "MVRV", tags: ["on-chain","valuation","long_term_holder","cohorts","profit_loss","unrealized_profit_loss"] },
  { path: "/market/mvrv_z_score", name: "MVRV Z-Score", group: "MVRV", tags: ["on-chain","valuation","profit_loss","unrealized_profit_loss"] },
  { path: "/market/price_drawdown_relative", name: "Price Drawdown from ATH", group: "Price", tags: ["spot","price"] },
  { path: "/market/price_realized_usd", name: "Realized Price", group: "Realized Cap & Price", tags: ["on-chain","price","valuation"] },
  { path: "/market/price_usd_close", name: "Price", group: "Price", tags: ["spot","price"] },
  { path: "/market/price_usd_ohlc", name: "Price OHLC", group: "Price", tags: ["spot","price"] },
  { path: "/market/realized_volatility_1_month", name: "Annualized Realized Volatility (1 Month)", group: "Volatility", tags: ["spot","volatility","realized_volatility"] },
  { path: "/market/realized_volatility_1_week", name: "Annualized Realized Volatility (1 Week)", group: "Volatility", tags: ["spot","volatility","realized_volatility"] },
  { path: "/market/realized_volatility_1_year", name: "Annualized Realized Volatility (1 Year)", group: "Volatility", tags: ["spot","volatility","realized_volatility"] },
  { path: "/market/realized_volatility_2_weeks", name: "Annualized Realized Volatility (2 Weeks)", group: "Volatility", tags: ["spot","volatility","realized_volatility"] },
  { path: "/market/realized_volatility_3_months", name: "Annualized Realized Volatility (3 Months)", group: "Volatility", tags: ["spot","volatility","realized_volatility"] },
  { path: "/market/realized_volatility_6_months", name: "Annualized Realized Volatility (6 Months)", group: "Volatility", tags: ["spot","volatility","realized_volatility"] },
  { path: "/market/realized_volatility_all", name: "Annualized Realized Volatility (All)", group: "Volatility", tags: ["spot","volatility","realized_volatility"] },
  { path: "/mempool/fees_distribution", name: "Mempool Total Amount of Fees by Relative Fee (Sat / vByte)", group: "Mempool", tags: ["on-chain","mempool","fees"] },
  { path: "/mempool/fees_sum", name: "Mempool Total Amount of Fees", group: "Mempool", tags: ["on-chain","mempool","fees"] },
  { path: "/mempool/txs_count_distribution", name: "Mempool Number of Transactions by Relative Fee (Sat / vByte)", group: "Mempool", tags: ["on-chain","mempool"] },
  { path: "/mempool/txs_count_sum", name: "Mempool Total Number of Transactions", group: "Mempool", tags: ["on-chain","mempool"] },
  { path: "/mempool/txs_size_distribution", name: "Mempool Total Size of Transactions by Relative Fee (Sat / vByte)", group: "Mempool", tags: ["on-chain","mempool"] },
  { path: "/mempool/txs_size_sum", name: "Mempool Total Size of Transactions", group: "Mempool", tags: ["on-chain","mempool"] },
  { path: "/mining/difficulty_latest", name: "Mining Difficulty", group: "Difficulty & Hashrate", tags: ["on-chain","mining"] },
  { path: "/mining/hash_rate_mean", name: "Mean Hash Rate", group: "Difficulty & Hashrate", tags: ["on-chain","mining"] },
  { path: "/mining/marketcap_thermocap_ratio", name: "Market Cap to Thermocap Ratio", group: "Fees", tags: ["on-chain","mining","valuation"] },
  { path: "/mining/revenue_from_fees", name: "Percent Miner Revenue from Fees", group: "Miner Revenue", tags: ["on-chain","mining","fees"] },
  { path: "/mining/revenue_sum", name: "Total Miner Revenue", group: "Miner Revenue", tags: ["on-chain","mining"] },
  { path: "/mining/thermocap", name: "Aggregate Security Spend (Thermocap)", group: "Fees", tags: ["on-chain","mining","valuation"] },
  { path: "/mining/volume_mined_sum", name: "Total Miner Revenue from Block Rewards", group: "Miner Revenue", tags: ["on-chain","mining"] },
  { path: "/options/options_volume", name: "Options Volume", group: "Volume", tags: ["options","volume"] },
  { path: "/supply/active_1d_1w", name: "Total Supply Last Active 1d-1w", group: "HODL Waves", tags: ["on-chain","supply","cohorts"] },
  { path: "/supply/active_1m_3m", name: "Total Supply Last Active 1m-3m", group: "HODL Waves", tags: ["on-chain","supply","cohorts"] },
  { path: "/supply/active_1w_1m", name: "Total Supply Last Active 1w-1m", group: "HODL Waves", tags: ["on-chain","supply","cohorts"] },
  { path: "/supply/active_1y_2y", name: "Total Supply Last Active 1y-2y", group: "HODL Waves", tags: ["on-chain","supply","cohorts"] },
  { path: "/supply/active_24h", name: "Total Supply Last Active < 24h", group: "HODL Waves", tags: ["on-chain","supply","cohorts"] },
  { path: "/supply/active_2y_3y", name: "Total Supply Last Active 2y-3y", group: "HODL Waves", tags: ["on-chain","supply","cohorts"] },
  { path: "/supply/active_3m_6m", name: "Total Supply Last Active 3m-6m", group: "HODL Waves", tags: ["on-chain","supply","cohorts"] },
  { path: "/supply/active_3y_5y", name: "Total Supply Last Active 3y-5y", group: "HODL Waves", tags: ["on-chain","supply","cohorts"] },
  { path: "/supply/active_5y_7y", name: "Total Supply Last Active 5y-7y", group: "HODL Waves", tags: ["on-chain","supply","cohorts"] },
  { path: "/supply/active_6m_12m", name: "Total Supply Last Active 6m-12m", group: "HODL Waves", tags: ["on-chain","supply","cohorts"] },
  { path: "/supply/active_7y_10y", name: "Total Supply Last Active 7y-10y", group: "HODL Waves", tags: ["on-chain","supply","cohorts"] },
  { path: "/supply/active_more_10y", name: "Total Supply Last Active 10y", group: "HODL Waves", tags: ["on-chain","supply","cohorts"] },
  { path: "/supply/active_more_1y_percent", name: "Percent of Supply Last Active 1+ Years Ago", group: "HODL Waves", tags: ["on-chain","supply","cohorts"] },
  { path: "/supply/active_more_2y_percent", name: "Percent of Supply Last Active 2+ Years Ago", group: "HODL Waves", tags: ["on-chain","supply","cohorts"] },
  { path: "/supply/active_more_3y_percent", name: "Percent of Supply Last Active 3+ Years Ago", group: "HODL Waves", tags: ["on-chain","supply","cohorts"] },
  { path: "/supply/active_more_5y_percent", name: "Percent of Supply Last Active 5+ Years Ago", group: "HODL Waves", tags: ["on-chain","supply","cohorts"] },
  { path: "/supply/burn_rate", name: "Burn Rate (Base Fee)", group: "Fees", tags: ["on-chain","supply","fees","gas"] },
  { path: "/supply/burned", name: "Burned Supply", group: "Supply Dynamics", tags: ["on-chain","supply"] },
  { path: "/supply/current", name: "Circulating Supply", group: "Circulating Supply", tags: ["on-chain","supply"] },
  { path: "/supply/current_adjusted", name: "Adjusted Circulating Supply", group: "Circulating Supply", tags: ["on-chain","supply"] },
  { path: "/supply/hodl_waves", name: "HODL Waves", group: "HODL Waves", tags: ["on-chain","supply","cohorts"] },
  { path: "/supply/inflation_rate", name: "Inflation Rate", group: "Issuance", tags: ["on-chain","supply","network_statistics"] },
  { path: "/supply/issued", name: "Issuance", group: "Issuance", tags: ["on-chain","supply","network_statistics"] },
  { path: "/supply/loss_sum", name: "Total Supply in Loss", group: "Supply in Profit/Loss", tags: ["on-chain","supply","profit_loss","unrealized_profit_loss"] },
  { path: "/supply/lth_net_change", name: "Long-Term Holder Net Position Change", group: "Supply", tags: ["on-chain","supply","long_term_holder","cohorts"] },
  { path: "/supply/lth_sum", name: "Total Supply Held by Long-Term Holders", group: "Supply", tags: ["on-chain","supply","long_term_holder","cohorts"] },
  { path: "/supply/minted", name: "Minted Supply", group: "Issuance", tags: ["on-chain","supply","network_statistics"] },
  { path: "/supply/probably_lost", name: "Probably Lost Supply", group: "Lost Supply", tags: ["on-chain","supply","lifespan"] },
  { path: "/supply/profit_relative", name: "Percent Supply in Profit", group: "Supply in Profit/Loss", tags: ["on-chain","supply","profit_loss","unrealized_profit_loss"] },
  { path: "/supply/profit_sum", name: "Total Supply in Profit", group: "Supply in Profit/Loss", tags: ["on-chain","supply","profit_loss","unrealized_profit_loss"] },
  { path: "/supply/provably_lost", name: "Provably Lost Supply", group: "Lost Supply", tags: ["on-chain","supply"] },
  { path: "/supply/rcap_hodl_waves", name: "Realized Cap HODL Waves", group: "HODL Waves", tags: ["on-chain","supply","cohorts","valuation"] },
  { path: "/supply/sth_sum", name: "Total Supply Held by Short-Term Holders", group: "Supply", tags: ["on-chain","supply","short_term_holder","cohorts"] },
  { path: "/supply/supply_by_txout_type", name: "Supply by TxOut Type", group: "Transaction Types", tags: ["on-chain","supply"] },
  { path: "/supply/tips", name: "Tips (Priority Fee)", group: "Fees", tags: ["on-chain","fees"] },
  { path: "/transactions/contract_calls_external_count", name: "Total Number of Contract Calls (External)", group: "Transaction Types", tags: ["on-chain","transactions"] },
  { path: "/transactions/contract_calls_internal_count", name: "Total Number of Contract Calls (Internal)", group: "Transaction Types", tags: ["on-chain","transactions"] },
  { path: "/transactions/count", name: "Number of Transactions", group: "Transaction Count", tags: ["on-chain","transactions"] },
  { path: "/transactions/rate", name: "Number of Transactions per Second", group: "Transaction Count", tags: ["on-chain","transactions"] },
  { path: "/transactions/segwit_adoption", name: "SegWit Adoption", group: "Transaction Types", tags: ["on-chain","transactions","network_statistics"] },
  { path: "/transactions/size_mean", name: "Mean Size of Transfers", group: "Transaction Size", tags: ["on-chain","transactions","network_statistics"] },
  { path: "/transactions/size_sum", name: "Total Size of Transactions", group: "Transaction Size", tags: ["on-chain","transactions","network_statistics"] },
  { path: "/transactions/spent_output_types_share", name: "Spent Output Types", group: "Transaction Types", tags: ["on-chain","transactions","network_statistics"] },
  { path: "/transactions/taproot_adoption", name: "Taproot Adoption", group: "Transaction Types", tags: ["on-chain","transactions","network_statistics"] },
  { path: "/transactions/transfers_count", name: "Number of Transfers", group: "Transaction Count", tags: ["on-chain","transactions"] },
  { path: "/transactions/transfers_count_nfts", name: "NFTs Transactions (Absolute)", group: "Transaction Types", tags: ["on-chain","transactions"] },
  { path: "/transactions/transfers_count_nfts_relative", name: "NFTs Transactions (Relative)", group: "Transaction Types", tags: ["on-chain","transactions"] },
  { path: "/transactions/transfers_from_exchanges_count", name: "Number of Transfers from Exchanges", group: "Exchange Flows", tags: ["on-chain","transactions","exchanges"] },
  { path: "/transactions/transfers_rate", name: "Number of Transfers per Second", group: "Transaction Count", tags: ["on-chain","transactions"] },
  { path: "/transactions/transfers_to_exchanges_count", name: "Number of Transfers to Exchanges", group: "Exchange Flows", tags: ["on-chain","transactions","exchanges"] },
  { path: "/transactions/transfers_volume_adjusted_mean", name: "Mean Transfer Volume (Change-Adjusted)", group: "Transfer Volume", tags: ["on-chain","transactions","volume"] },
  { path: "/transactions/transfers_volume_adjusted_median", name: "Median Transfer Volume (Change-Adjusted)", group: "Transfer Volume", tags: ["on-chain","transactions","volume"] },
  { path: "/transactions/transfers_volume_adjusted_sum", name: "Total Transfer Volume (Change-Adjusted)", group: "Transfer Volume", tags: ["on-chain","transactions","volume"] },
  { path: "/transactions/transfers_volume_exchanges_net", name: "Net Transfer Volume from/to Exchanges", group: "Exchange Flows", tags: ["on-chain","transactions","volume","exchanges"] },
  { path: "/transactions/transfers_volume_from_exchanges_mean", name: "Mean Transfer Volume from Exchanges", group: "Exchange Flows", tags: ["on-chain","transactions","volume","exchanges"] },
  { path: "/transactions/transfers_volume_from_exchanges_sum", name: "Total Transfer Volume from Exchanges", group: "Exchange Flows", tags: ["on-chain","transactions","volume","exchanges"] },
  { path: "/transactions/transfers_volume_mean", name: "Mean Transfer Volume", group: "Transfer Volume", tags: ["on-chain","transactions","volume"] },
  { path: "/transactions/transfers_volume_median", name: "Median Transfer Volume", group: "Transfer Volume", tags: ["on-chain","transactions","volume"] },
  { path: "/transactions/transfers_volume_sum", name: "Total Transfer Volume", group: "Transfer Volume", tags: ["on-chain","transactions","volume"] },
  { path: "/transactions/transfers_volume_to_exchanges_mean", name: "Mean Transfer Volume to Exchanges", group: "Exchange Flows", tags: ["on-chain","transactions","volume","exchanges"] },
  { path: "/transactions/transfers_volume_to_exchanges_sum", name: "Total Transfer Volume to Exchanges", group: "Exchange Flows", tags: ["on-chain","transactions","volume","exchanges"] },
  { path: "/transactions/tx_types_breakdown_count", name: "Ethereum Transaction Type Breakdown (Absolute)", group: "Transaction Types", tags: ["on-chain","transactions"] },
  { path: "/transactions/tx_types_breakdown_relative", name: "Ethereum Transaction Type Breakdown (Relative)", group: "Transaction Types", tags: ["on-chain","transactions"] },
  { path: "/treasuries/balance_companies", name: "Treasury Balances (Companies)", group: "Public Companies", tags: ["treasuries","companies","entities","institutions"] },
  { path: "/treasuries/balance_governments", name: "Treasury Balances (Governments)", group: "Strategic Reserves", tags: ["treasuries","governments","entities"] },
];

/** O(1) membership test for the advanced (x402-reachable) metric paths. */
export const X402_METRIC_SET: ReadonlySet<string> = new Set(X402_CATALOG.map((e) => e.path));
